1 html/2 form
AntipovSergey/Purpleschool-html-css pull request #2
Opened 2023-11-26 11:56 UTC by AntipovSergey

2023-11-26 22:40 UTC, Levitinn requested changes

2023-11-26 22:40 UTC, Levitinn commented on form.html
> +        <div>
безсмысленный див

2023-11-26 22:40 UTC, Levitinn commented on form.html
> +        <div>
ниже так же встречается

2023-11-26 22:40 UTC, Levitinn commented on form.html
> +        <button>Зарегистрироваться</button>
type="submit"

2023-11-26 22:40 UTC, Levitinn commented on index.html
> +        <img src="./images/computer.jpg" alt="Изображение компьютера" />
каждый img стоит оборачивать в див

2023-11-27 17:31 UTC, AntipovSergey commented on form.html
> +        <div>
А какой конкретно див бессмыслен? Который оборачивает <p> и <a>?

2023-11-27 17:40 UTC, AntipovSergey commented on form.html
> +        <div>
Еще один вопрос. У меня изначально был пулреквест из ветки 1-html/1-Blog. Когда я сделал ветку 1-html/2-Form, у меня создался новый пулреквест, в котором появились коммиты к изменениям из первого дз по верстке блога и коммит к изменениям из второго дз по верстке формы. Когда все замечания по верстке будут исправлены и Вы смержете пулреквест, нужно будет сделать pull из ветки этого пулреквеста на develop, верно? Как тогда быть с первым пулреквестом?

2023-11-28 19:22 UTC, Levitinn requested changes

2023-11-28 19:22 UTC, Levitinn commented on form.html
> +        <div>
> А какой конкретно див бессмыслен? Который оборачивает тэг p и тэг a. или который оборачивает label?

инпуты обычно оборачивают в див или label, в твоем случае, лейбл уже есть, потому див лишний

2023-11-28 19:22 UTC, Levitinn commented on form.html
> +        <div>
> Еще один вопрос. У меня изначально был пулреквест из ветки 1-html/1-Blog. Когда я сделал ветку 1-html/2-Form, у меня создался новый пулреквест, в котором появились коммиты к изменениям из первого дз по верстке блога и коммит к изменениям из второго дз по верстке формы. Когда все замечания по верстке будут исправлены и Вы смержете пулреквест, нужно будет сделать pull из ветки этого пулреквеста на develop, верно? Как тогда быть с первым пулреквестом?

после аврува МР, который я ставлю, те сам делаешь мерж. это обновляет твой девелоп.
а другая ветка, которая так же ожидает МР в девелоп не должна вызвать конфликты, так как ее изменения будут новее. если же конфликты все же появятся,  тебе стоит зайти в вскоде в девелоп, сделать гит пулл, после этого переключиться в ту ветку, и сделать git merge develop.  решить конфликты и снова запушить в эту ветку(удаленную) этот второй коммит (в котором решены конфликты) появится в том же МР.

по опыту скажу, сложно студентам объяснить что то про гит, так что если все таки возникнут вопросы при слиянии, пиши в дискорд

2023-11-29 18:02 UTC, Levitinn approved these changes
молодец) про button type="submit" я погорячился. оказывается, с теперь, если button один, внутри формы,  то он автоматически считается type=submit

2024-07-01 12:09 UTC, closed without merging